### ISSUE TITLE
rvm update from 1.9.3 to 2.1.5 to metasploit environment 

### ISSUE THREAD

**Issue by coldalfred** [Veil-Framework/Veil-Evasion#121]
Hi community,

Ill update from 1.9.3 to 2.1.5 on RVM from this guide

https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment 

So i get this error when ill try to build from ruby payload list...

C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/dependency.rb:247:in `to_specs': Could not find ocra (>= 0) amongst [] (Gem::LoadError)
	from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/dependency.rb:256:in `to_spec'
	from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:1231:in `gem'
	from /root/.wine/drive_c/Ruby187/bin/ocra:22

I hope you can help me with that.. if i try to change to the right version the error disappear and anything work perfect with pure ruby payload and not shellcode but i can't find a fast solution to msfvenom work without 2.1.5

Sorry for my bad english,
Thanks

**Comment by ChrisTruncer** [comment]
Hi, As far as I knew, your wine environment should be separate from your main OS.  So, updating ruby in Kali wouldn't impact Wine (I believe this is correct, someone let me know if I am wrong).  I'm not sure the best way to fix this, I think it is isolated to your install.  Because of that, I'm going to close this out, I don't believe this is a Veil issue.  However, if we can somehow learn/see that it is, then I'll be happy to re-open it to address it then.
