### ISSUE TITLE
0 payload modules available in Veil Evasion after apt-get install of veil-evasion on Kali

### ISSUE THREAD

**Issue by NerishiQaMaster** [Veil-Framework/Veil-Evasion#157]
Hi,

Whilst trying to troubleshoot a problem on Kali Linux x86 - "Generate" command causes crash of Veil Evasion - I removed and reinstalled veil-evasion, using apt-get remove & apt-get install respectively.

When I then run the command "veil-evasion", the menu opens showing 0 (zero) payloads available.
Setup,.sh also generates an error - raised here https://github.com/Veil-Framework/Veil-Evasion/issues/156.

It's all gone a bit wrong, with a sense there is one underlying root cause. But I'm likely incapable of identifying it myself.
Lil' help, anyone?

Many thanks for your time,

Nerishi

**Comment by ChrisTruncer** [comment]
It might be best for you to start on a clean VM.  Please only clone this from github, and then setup/use from the cloned repo.

When you do this, you will need to run the setup script.  It will call the update script, and then you should have all the payloads listed.  If you have 0 payloads listed, it's because your config file is incorrect.

**Comment by sailor234** [comment]
To fix this I did "sudo apt-get purge veil-evasion" and when that was finished I reinstalled it by running "sudo apt-get install veil-evasion".

**Comment by Blackmase** [comment]
had the same issue but fixed it by copying the clipboard link from git hub and pasted to terminal. Just type the following in terminal;
git clone 'paste your link here' (hit enter )
then change directory to /root/Veil-Evasion/setup/./setup.sh -s (hit enter)
Leave it to finish installing and probably you will be requested to install some python and ruby.
And your done!
DO NOT MOVE YOUR VEIL FOLDER TO ANOTHER FOLDER...I did that and after running  ./Veil-Evasion.py    i got 0 payloads. But after moving it back to the root folder all my payloads were active.

**Comment by stefanusayudha** [comment]
hi all.. first im sorry about my language cz im not an english, secondly i had same issue.. n i get i work again after i edit my configuration script.. in /etc/veil/settings.py at line PAYLOAD_SOURCE_PATH , and set it directly to /opt/metasploit-framework/embedded/framework where the payloads stored and it working again.. each time u do an upate for configuration, the payloads path conf will reset so u need to manualy set it again

**Comment by sherwyn18** [comment]
i had the same problem with having 'o payload in Veil-Evasion'.initially i installed it two different ways(because of problem); one using the git clone htttp://...... and apt-get install Veil-Evasion . so after going through the process of installing Veil-Evasion about three different times having the same pronlem then i uninstalled Veil-Evasion using apt-get autoremove and the purge method then installed it again from github using the git clone method and the apt-get Veil-Evasion( installd it twice just to be sure). later i realized there had a folder named 'Veil' and 'Veil-Evasion' so i put the 'Veil-Evasion 'folder in the 'Veil' folder. then i uninstalled it again using both methods again and installed it using both methods and now its working as intended. 
i.e put one folder in other uninstall then install using ./setup.sh
hope  it help someone

**Comment by VillaStrayligh7** [comment]
I had the same issue with the latest version of Kali 2017.1.  I initially installed Veil-Evasion by cloning it directly from GitHub (git clone  https://github.com/Veil-Framework/Veil-Evasion) and then running the setup.sh script.  setup.sh reporting everything installed fine, but when running ./Veil-Evasion.py I would get "0 payloads loaded".  So I tried a variation on sherwyn18's post and then installed veil-evasion via apt-get (apt-get install veil-evasion).  Then ran veil-evasion (apt-get version) which the first time you run it it goes through the setup automatically.  On that initial run I got "0 payloads loaded", but then I exit and run veil-evasion again and bingo, I get "51 payloads loaded".  I then went back to my git clone version of Veil-Evasion running it, and again "51 payloads loaded" in that one too.  So something that the apt-get installer does on Kali that fixes it.
