### ISSUE TITLE
[WishList] Adding upstream

### ISSUE THREAD

**Issue by g0tmi1k** [Veil-Framework/Veil-Evasion#191]
Is it worth adding any of the following upstream, into Veil-Evasion itself?

+ Powershell - https://raw.githubusercontent.com/benpturner/h00k/master/python/macro_safe.py
+ New payload - https://github.com/codewatchorg/SideStep
+ Web UI - https://github.com/tomsteele/veil-evasion-api

**Comment by ChrisTruncer** [comment]
I think the powershell one is a definite candidate to get added in.  It might work best almost as a "required option" where it will allow powershell scripts to be macro safe.

SideStep is an issue.  I tried looking into this, but a problem with it is they modify the standard pydasm library (I believe it was that lib) in order to run.  I'm hesitant to modify library's and install the modified versions on user's workstations since it could mess up any other script/app that calls that same function.  Thoughts?

I haven't messed with the WebUI yet.  I'll need to look into that.

**Comment by tomsteele** [comment]
If anyone wants to have a conversation about the Web UI I'd be happy to have it. Just let me know the time and the place. It's something I built in a few hours, but would be happy to contribute more to the effort.

**Comment by ChrisTruncer** [comment]
I'm going to close this for now.  The PowerShell module has been added in (or a module with the same functionality).  SideStep seems to have some modifications to a library that I don't necessarily want to completely add in since it would impact anyone attempting to use that library (or so it appears).  The Web-UI we can look into at some point, but I'd prefer to wait until a new version of Veil is released so we don't spend a ton of time on it right now to have to duplicate the effort.

Once Veil 3 is released, it's definitely worth looking into.
