### ISSUE TITLE
Msfvenom Extra options

### ISSUE THREAD

**Issue by solidairo** [Veil-Framework/Veil-Evasion#220]
Hey there, having issue with veil-evasion adding extra msfvenom options. Tried with python/shellcode_inject/base64_substitution didn't use_pyherion and added 2 extra msfvenom options like (x=/root/Desktop/chrome.exe) and (k=) using Veil-Evasion version 2.22.1. Tried also same options with python/shellcode_inject/aes_encrypt without any success. Thanks for help.

![problem](https://cloud.githubusercontent.com/assets/14822967/10076337/c0ccfee6-62e3-11e5-91d2-836b5a2593d1.jpg)

**Comment by ChrisTruncer** [comment]
What happens when this runs?

To be honest, I don't think this will work because Veil-Evasion works to generate new executables, and not backdoor existing ones.  If you are looking to backdoor an existing executable, I'd highly recommend Backdoor Factory by @secretsquirrel (and he very conveniently has created a module for us to include it in Veil-Evasion).  However, the latest version is also in his github page.
