### ISSUE TITLE
Internal Error #2

### ISSUE THREAD

**Issue by JustDennis** [Veil-Framework/Veil-Evasion#259]
Hey Veil-Evasion Team,
I got one question, if I try to creat a payload via Veil-Evasion (only if its for 64bit. For 32bit payloads everything is working fine.) Using following command: ./Veil-Evasion.py ; list ; 34 ; set ARCHITECTURE 64 ; set USE_PYHERION Y; aswell LHOST and LPORT, and then generate i can choose the name and how to creat the executable (only 1 option "Pyinstaller") after i press enter i get following error : "ERROR: Unable to create output file. Internal error #2. Unable to generate output. Please run /root/Veil-Evasion/config/update.py manually"

I already run update.py manually, nothing happens. I did reinstall Veil-Evasion. And Python in my wine aswell. I even tried it on a clean Kali VM too, with the same error. If I try to generate a 32bit payload I get no problems. 
Any ideas?

Best regards

**Comment by ChrisTruncer** [comment]
64 bit python payloads requires 64 bit wine and 64 bit python installed within wine.  By default, we only install 32.

**Comment by ChrisTruncer** [comment]
If you need me to elaborate or help answer anything else, just let me know

**Comment by JustDennis** [comment]
Just wanted to say Thank you for the fast answer, was over the days not at home. I'll remember it if I need your help. :D

**Comment by JustDennis** [comment]
Another Question: I actually installed now Python 64 bit via "WINEPREFIX=~/.wine64 winearch=win64 wine64 msiexec /i Downloads/python-2.7.5.amd64.msi" everythin worked well. But I get still the same error, is there anything else i need to look at?

**Comment by ChrisTruncer** [comment]
I’m not certain at the moment to be honest because I never use 64 bit payloads with Veil.  I’d be really interested if you do get it working to document that info.  I’ll try to get to look at it at some point, but right now there’s updates and other things I have to prioritize.


-----------------------------------------------------------------------------------------
Christopher Truncer
@christruncer

On January 26, 2016 at 11:42:01 AM, JustDennis (notifications@github.com) wrote:

Another Question: I actually installed now Python 64 bit via "WINEPREFIX=~/.wine64 winearch=win64 wine64 msiexec /i Downloads/python-2.7.5.amd64.msi" everythin worked well. But I get still the same error, is there anything else i need to look at?
