### ISSUE TITLE
Pyinstaller compatibility issues in Kali

### ISSUE THREAD

**Issue by sbrun** [Veil-Framework/Veil-Evasion#284]
Hi,
## Veil-Evasion version
2.24
## OS Used - all info (architecture, linux flavor, etc)
Kali-rolling

I updated veil-evasion package in kali-rolling from version 2.23 to 2.24.
I had a problem with pyinstaller:

1. The new version in kali (3.1.1-0kali2) installs pyinstaller in the correct directory for a python module in /usr/share/python2.7/dist-packages/PyInstaller/.  (the previous version of pyinstaller in kali was not installed in the correct directory).
But in config/update.py you are looking for a directory in /usr/share/pyinstaller, and if it doesn't exist, it's configured to use /opt/pyinstaller-2.0/.

2. In pyinstaller, there is no usr/share/python2.7/dist-packages/PyInstaller/pyinstaller.py but a /usr/bin/pyinstaller instead. 

3. Even when I'm installing "your" pyinstaller version with the setup/setup.sh in /usr/share/pyinstaller, I had the same problem than mentioned in issue #268
```
cp: can not create file regulate '/usr/share/pyinstaller/support/loader/Windows-32bit/runw.exe': No such file
```
And the same problem of path will appear with the pyinstaller package in kali: there is no 
/usr/lib/python2.7/dist-packages/PyInstaller/support/loader/Windows-32bit/runw.exe but a /usr/lib/python2.7/dist-packages/PyInstaller/bootloader/Windows-32bit/run.exe

At this moment the package in kali is installing pyinstaller  thanks to the setup/setup.sh (with problem of path '/usr/share/pyinstaller/support/loader/Windows-32bit/runw.exe' fixed).
But it will be better if you can fix veil-evasion so it can use the packaged version of pyinstaller in kali-rolling.

cc @rhertzog

**Comment by ChrisTruncer** [comment]
I don't create any of the packages that bundle veil-evasion, I just maintain the code. You'd have to talk to the package maintainers to use an up to date version of veil-evasion.

**Comment by rhertzog** [comment]
Hello @ChrisTruncer, we know that. We are the Kali packagers and we ask you — as upstream authors — to consider adjusting your setup.sh to install pyinstaller like any other python package (via pip possibly?) so that the installation that you would use in your code would be the same that we use in Kali in the official package and so that we don't have to patch your code in the future.

Right now we apply the following changes:
http://git.kali.org/gitweb/?p=packages/veil-evasion.git;a=blob;f=debian/patches/Update-configuration-script.patch;h=c2f76d24a942ed1c731ba40a4604ec25f5259c7e;hb=1a8769338e5892806b73ce3420c4810dce745df5
http://git.kali.org/gitweb/?p=packages/veil-evasion.git;a=blob;f=debian/patches/upgrade-setup-file.patch;h=e5e4bb057781a8125d0faa9139bb83924f4a3c0c;hb=1a8769338e5892806b73ce3420c4810dce745df5

We would prefer to not have to install Pyinstaller in /usr/share/PyInstaller and instead use the system-wide python-pyinstaller available in the Python library path.

**Comment by gordonrs** [comment]
@rhertzog This is currently being worked on by myself as part of an effort to clean up the installer and add further distribution support for Veil. As soon as testing is complete and everything signed off on the initial PR, the PyInstaller changes will be made in setup.sh to clean up the "filesystem spray" that happens during the install.

**Comment by ChrisTruncer** [comment]
@rhertzog - I will check on pyinstaller again, but the version that was packaged for rolling, I can't seem to get working with Veil-Evasion which is why I am installing pyinstaller as it is.

I'm working with @gordonrs to look at the setup script, and if we are able to leverage the packaged pyinstaller, that's definitely my preference.  So I am happy to look into it.

**Comment by amainyebriggs** [comment]
1.download a new pyinstaller from https://github.com/pyinstaller/pyinstaller/releases/download/v3.1.1/PyInstaller-3.1.1.tar.gz

 2.   rm -r /usr/share/pyinstaller
 3. extract PyInstaller-3.1.1 to /usr/share
 4.   rename PyInstaller-3.1.1 in /usr/share to pyinstaller 
 5.cd /usr/share/pyinstaller
 6. python setup.py install 
7.cd /usr/share/veil-evasion/config 
8.python update.py

that will fix it

**Comment by hatlord** [comment]
You can just add the directory and the error goes away:

mkdir /usr/share/pyinstaller/support/loader/Windows-32bit/

**Comment by ChrisTruncer** [comment]
@sbrun you ok now?  Will close this shortly if we don't hear back

**Comment by sbrun** [comment]
Have you made any change so that veil-evasion works with packaged pyinstaller?
If no, I suggest to keep this issue open until it's fixed.

**Comment by amainyebriggs** [comment]
am still have that issue
![screenshot from 2016-03-08 22-03-25](https://cloud.githubusercontent.com/assets/13424678/13698860/1252d8b8-e777-11e5-8e04-cd7d0af3b935.png)

**Comment by hatlord** [comment]
Different issue. You need to go here:

https://github.com/Veil-Framework/Veil-Evasion/issues/282

And read the fix at the bottom.

**Comment by ChrisTruncer** [comment]
OK, so we merged in one cleanup of the setup script thanks to @gordonrs.  I'll try to check out the pyinstaller issue now.  One thing that seemed odd, is when using the python package in apt, I wasn't able to get pyinstaller to "compile" the python payloads veil-evasion creates, I could only do it using the method currently in the setup script.

Now, it's possible the cleanup somehow fixed the issue, so I'll check it out.

**Comment by ChrisTruncer** [comment]
@sbrun and @rhertzog First, thanks for the patience with this.  I started looking at some of the patches you are making to the setup and update scripts.  First question, looks like you're changing output from /usr/share to /var/lib...., should that be the proper location?  Funny thing is the reason we switched to use /usr/share (a while ago) was because when talking with a couple Kali guys, they said that would be the proper directory.

I don't mind starting to make changes that will help your end too, just want to verify before I start doing some of them.  I know @gordonrs has helped a ton, and he might chime in too at some point, but figured I'd ask you guys before I start making mods to the code.

**Comment by rhertzog** [comment]
The proper location is defined by the Filesystem Hierarchy Standard: http://refspecs.linuxfoundation.org/fhs.shtml

Quoting it: 
> /var contains variable data files. This includes spool directories and files, administrative and logging data, and transient and temporary files.

So output files definitely belong to /var since they are not "permanent". We opted to ure /var/lib as we want to ensure that the generated data is kept. If the data is only "transient", then it might be better to use /var/cache instead.

In any case, Python source code is permanent and can be shared across architectures so its place is in /usr/share/.

**Comment by gordonrs** [comment]
The way I was thinking of breaking it up was to try and make everything as clean and as standard as possible so that things for the git users wasn't run out of the repo directory structure. On initial setup, I'd have Veil copied to a location so it was available system wide to all users. I recognise that is not exactly our usage case here, but I think it's what packagers expect.

What I'm trying to do is actually get away from everything being done inside the home directory entirely. The main reason I started this is that I had something else I was working on mess up Veil, so I wanted to partition it off completely.

This is kind of tricky though since by the very nature of Veil's setup process it's somewhat archaic in where everything goes. We have the new per-user wine environments which is really the first step in cleaning a lot of this shit up, but these changes also enable there to be a _global veil wine environment._ I'm assuming that this is something that you guys in Kali would be interested in as part of cleaning it up. So instead of installing everything inside `$HOME/.config/wine/veil/ `(or `/root/.wine/`) as it used to be when installed in Kali, you would be able to once all the rest of the required work has been completed have something like `/usr/libexec/veil` or `/var/lib/veil/env`. Obviously, I'd like us to be able to all use the same location for all of that stuff.

This somewhat complicates things because of /etc/veil/settings.py if someone has both a global and user home directory install, (such as dev's working on it) so I'm not against having a ~/.config/veil/settings.py and giving that precedence over the the one in /etc/ for non-root users, but I need to do more thinking on how I would like for all this to be structured before I ask Chris to sign off any of the further changes.

As for the PyInstaller specific stuff, as @ChrisTruncer says, he's having a problem using the Kali package for it as it fails to build window PE executables. I'm going to do some testing on this and see if we can get away with a workaround in just using PyInstaller from pip. If so, we'll go down that road and investigate the package issue later even though it is the preference to always use system packages.

As for the Go stuff. I want to change how we do that stuff and I'd prefer having that inside the wine environment instead of in /usr/src or /usr/local. I don't want to pollute the file system like that with windows binaries.

Ideally I'd like to have the clean-up project entirely finished by the end of the summer. Regrettably my time is limited right now due to an election campaign over the next 5 weeks so I can't just sit down for a few days and do all the things I want to on this. Writing the code is fast, but testing and installing Veil dozens of times takes forever. What would help though is getting input from what you guys feel about those proposed changes and us agreeing on which directory locations to use for Veil globally. To make it easy on you the packagers, I can add a flag to the installer so that it will always prefer the location that we can agree upon. Hopefully we can eliminate the need in the near future for you to make patches to the installer at all.

Let me know what you think. Cheers.

**Comment by ChrisTruncer** [comment]
@gordonrs - I think we're on the exact same page, so everything sounds great to me.  Now I'm just interested in what @sbrun and @rhertzog have to say.

**Comment by rhertzog** [comment]
@gordonrs All this looks good. Except for the pip usage. We should really find out the underlying problem which makes the packaged PyInstaller unfit... @ChrisTruncer can you explain us what does not work with the packaged version? If we have a minimal test case of something working with the embedded pyinstaller but not with the packaged one we can at least try to debug it.

**Comment by unknownish** [comment]
Can somebody help me with the pwnstaller.
# copy the original runw.exe into the proper location
                runwPath = settings.VEIL_EVASION_PATH+"tools/runw_orig.exe"
                os.system("cp "+runwPath+" " + settings.PYINSTALLER_PATH + **"support/loader/Windows-32bit/runw.exe**") 
 # copy the loader into the correct location
    os.system("mv runw.exe " + settings.PYINSTALLER_PATH + "support/loader/Windows-32bit/")

    print " [*] Pwnstaller runw.exe moved to "+ settings.PYINSTALLER_PATH + "support/loader/Windows-32bit/\n"

Whats the new directory at the new pyinstaller 3.1.1 for **support/loader/Windows-32bit/** ?
When I create a executable with pwnstaller it doesnt gets the icons from the icon folder it gets the default icon of the python.I think something is wrong with the directory and it doesnt uses the runw.exe that the pwnstaller created.
But when i change the directory "support/loader/Windows-32bit/\n" to pyinstaller/PyInstaller/bootloader/Windows-32bit/ it creates a executable with the selected icon but I think its not a working executable when i click the exe nothing starts at windows platform(checked task manager) and in kali it cant open the executable. Sorry for my bad english .Thank you for your help. @ChrisTruncer @sbrun @rhertzog @gordonrs

**Comment by unknownish** [comment]
Can somebody help me with the pyinstaller and pwnstaller.
                runwPath = settings.VEIL_EVASION_PATH+"tools/runw_orig.exe"
                os.system("cp "+runwPath+" " + settings.PYINSTALLER_PATH + **"support/loader/Windows-32bit/runw.exe**") 
 # copy the loader into the correct location
    os.system("mv runw.exe " + settings.PYINSTALLER_PATH + "support/loader/Windows-32bit/")

    print " [*] Pwnstaller runw.exe moved to "+ settings.PYINSTALLER_PATH + "support/loader/Windows-32bit/\n"

Whats the new directory at the new pyinstaller 3.1.1 for **support/loader/Windows-32bit/** ?
When I create a executable with pwnstaller it doesnt gets the icons from the icon folder it gets the default icon of the python.I think something is wrong with the directory and it doesnt uses the runw.exe that the pwnstaller created.
But when i change the directory "support/loader/Windows-32bit/\n" to pyinstaller/PyInstaller/bootloader/Windows-32bit/ it creates a executable with the selected icon but I think its not a working executable when i click the exe nothing starts at windows platform(checked task manager) and in kali it cant open the executable. Sorry for my bad english .Thank you for your help. @ChrisTruncer @sbrun @rhertzog @gordonrs

**Comment by ChrisTruncer** [comment]
OK,

So I did some testing, and I am still running into issues with the pyinstaller package that comes within Kali (via apt).  I printed out the command that Veil uses to generate a python package, and then modified it to use the pyinstaller that is installed via apt.  This link should show the errors:

http://pastebin.com/7L4PsjdA

If it's something off on my end, please let me know.  But this is the error I get when using pyinstaller installed via APT (a properly "compiled" python binary).  When I invoke it by calling the pyinstaller.py file in it's "pre-compiled" state, it works (currently how Veil-Evasion is doing it).

**Comment by ChrisTruncer** [comment]
Also a note, just to test/replicate this, you're going to have to download and install Veil-Evasion from this repo vs. the package in apt.

**Comment by ChrisTruncer** [comment]
@rhertzog and @sbrun - if there's anything I can do to help you replicate this, let me know.

**Comment by rhertzog** [comment]
@ChrisTruncer I'm sorry but I don't know anything about all this. To me it looks like you are trying use the Kali-packaged version of Pyinstaller from within wine. Why not install pyinstaller in the wine environment directly if that's where you want to use it?

Why do you have to run it in wine and not in Kali directly?

**Comment by ChrisTruncer** [comment]
@rhertzog that's basically what we are doing right now. Wine is invoking Python (installed in wine) to run the pyinstaller source code to package an executable. It's not actually installed in wine just because we've always had it work and never ran into issues while running the source code.

We have to run it in wine because pyinstaller makes an executable based off of the OS that has called Python. So in wine we can get Windows executables, if we used the native Python in Kali it would output elf files.

So going back to the original issue, I'm then not sure what we could do since we can't use the pyinstaller package in Kali's repos.

**Comment by ChrisTruncer** [comment]
Unless anyone has any suggestions, I think I will go ahead and close out this issue since it looks like we're not going to be able to use the currently packaged pyinstaller within apt.

**Comment by ChrisTruncer** [comment]
Ok, for now I am going to close this issue since it seems like there isn't a way to really fix it.  People can still comment on this, so if a fix arises in the future, I'd love to hear it.  But as of now it looks like the package within Kali isn't going to work for us.
