### ISSUE TITLE
Powershell Not Hidden

### ISSUE THREAD

**Issue by vendforce** [Veil-Framework/Veil-Evasion#325]
## Powershell version : 5.0

`powershell.exe  -W Hidden`

I upgraded powershell to framework 5.0 and it is now not been hidden . The cmd prompt pops up and holds for a couple of seconds I've tried using

` powershell.exe -WindowStyle Hidden`

But its still shows now for a split second and is not fully truly hidden

**Comment by ChrisTruncer** [comment]
Submit a patch?  I don't have a PowerShell v5 system right now to test on unfortunately.

**Comment by vendforce** [comment]
Yea Ill look into it, I know its not a part of the veil framwork or a bug in Veil, I was just reporting it .

**Comment by veil-evasion** [comment]
Ah, ok.  I wasn’t sure how to interpreter it.  Thanks for letting me know.

I’m on a plane right now so that’s why I don’t really have access to a system running it, and will be traveling over the weekend.  If you can see there’s a better way to call the payload, let me know and we can definitely get it added in.


-----------------------------------------------------------------------------------------
Christopher Truncer
@christruncer

On April 22, 2016 at 8:06:42 AM, vendforce (notifications@github.com) wrote:

Yea Ill look into it, I know its not a part of the veil framwork or a bug in Veil, I was just reporting it .
