### ISSUE TITLE
Invalid payload specified !

### ISSUE THREAD

**Issue by netdestroyer** [Veil-Framework/Veil-Evasion#341]
## Veil-Evasion version
2.26.4

## OS Used - all info (architecture, linux flavor, etc)
Kali rolling 2.0
## Pastebin link to error you are encountering (include console actions you took prior to error)
Use msfvenom or supply custom shellcode?

     1 - msfvenom (default)
Press [enter] for windows/meterpreter/reverse_tcp
[!] ERROR: Invalid payload specified!

## Any additional info you want to tell me
Path of msfvenom 
/opt/metasploit-framework/embedded/framework/

in settings.py : 
MSFVENOM_PATH = /usr/bin/

I try to change directory but i have the same error

**Comment by ChrisTruncer** [comment]
Please use Kali Rolling.  That’s the only version of Kali that we currently
support.


-----------------------------------------------------------------------------------------
Christopher Truncer
@christruncer <http://www.twitter.com/christruncer>

On May 27, 2016 at 9:32:07 AM, netdestroyer (notifications@github.com)
wrote:

Veil-Evasion version

2.26.4
OS Used - all info (architecture, linux flavor, etc)

Kali rolling 2.0
Pastebin link to error you are encountering (include console actions you
took prior to error)

Use msfvenom or supply custom shellcode?

 1 - msfvenom (default)

Press [enter] for windows/meterpreter/reverse_tcp
[!] ERROR: Invalid payload specified!
Expected behavior Any additional info you want to tell me

Path of msfvenom
/opt/metasploit-framework/embedded/framework/

in settings.py :
MSFVENOM_PATH = /usr/bin/

I try to change directory but i have the same error

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Veil-Framework/Veil-Evasion/issues/341>, or mute the
thread
<https://github.com/notifications/unsubscribe/ABmORrCrSpAfHxpdvllplxm3QA2nwL-2ks5qFw5ygaJpZM4IonS6>
.

**Comment by netdestroyer** [comment]
cat /etc/issue
Kali GNU/Linux Rolling \n \l

**Comment by netdestroyer** [comment]
I use kali rolling

**Comment by ChrisTruncer** [comment]
The problem is your metasploit path.  That's what Veil-Evasion uses to select the correct payload.  Please set the correct path.

**Comment by ChrisTruncer** [comment]
For example:

METASPLOIT_PATH="/usr/share/metasploit-framework/"

**Comment by netdestroyer** [comment]
ok , resolved

 i change the METASPLOIT_PATH="/opt/metasploit-framework/embedded/framework

now work it !!! thanks so much

**Comment by hytd** [comment]
where settings is?
