### ISSUE TITLE
Veil-Evasion Can't Create 64bit Payloads.

### ISSUE THREAD

**Issue by Illurity** [Veil-Framework/Veil-Evasion#343]
## Veil-Evasion version
2.26.4

## OS Used - all info (architecture, linux flavor, etc)
Kali Linux 2.0

## Pastebin link to error you are encountering (include console actions you took prior to error)
The program works fine as long as I'm not trying to use 64bit architecture, but as soon as I try to, it cannot create the payload. I am aware the LHOST in the paste says 0.0.0.0, I did that just for the 
paste. Here is the link to the pastebin.

http://pastebin.com/wMdyk5Te

## Expected behavior
It won't create a payload with 64bit architecture.

## EDIT ##
I followed these instructions 

download a new pyinstaller from https://github.com/pyinstaller/pyinstaller/releases/download/v3.1.1/PyInstaller-3.1.1.tar.gz

rm -r /usr/share/pyinstaller
extract PyInstaller-3.1.1 to /usr/share
rename PyInstaller-3.1.1 in /usr/share to pyinstaller 
cd /usr/share/pyinstaller
python setup.py install 
cd /usr/share/veil-evasion/config 
python update.py

And now I am getting the following error
cp: cannot create regular file ‘/usr/share/pyinstaller/support/loader/Windows-32bit/runw.exe’: No such file or directory
Traceback (most recent call last):
  File "Veil-Evasion.py", line 339, in <module>
    controller.MainMenu(args=args)
  File "/root/Veil-Evasion/modules/common/controller.py", line 875, in MainMenu
    self.outputFileName = self.PayloadMenu(self.payload, args=args)
  File "/root/Veil-Evasion/modules/common/controller.py", line 806, in PayloadMenu
    return self.OutputMenu(payload, payloadCode, args=args)
  File "/root/Veil-Evasion/modules/common/controller.py", line 612, in OutputMenu
    supportfiles.supportingFiles(self.payload, OutputFileName, {})
  File "/root/Veil-Evasion/modules/common/supportfiles.py", line 129, in supportingFiles
    and not os.path.isfile(settings.WINEPREFIX + 'drive_c/Python27/python.exe')):
AttributeError: 'module' object has no attribute 'WINEPREFIX'

**Comment by ChrisTruncer** [comment]
You’re correct in its current setup.  Veil-Evasion installs 32 bit wine.  I
am assuming you are generating a python based payload.  The way pyinstaller
works is it create the same payload architecture that it is currently
running on. Unfortunately, we can’t install both 32 and 64 bit wine
(obviously).  So as the setup script current works, you can only generate
32 bit payloads.  However, you could use the 64 bit source output to
generate x64 payload on a x64 windows system (or wine install with all its
dependencies) to make it. I wish I could give better info, but that’s the
way its current state generates payloads.


-----------------------------------------------------------------------------------------
Christopher Truncer
@christruncer <http://www.twitter.com/christruncer>

On May 30, 2016 at 6:24:53 PM, Illurity (notifications@github.com) wrote:

Veil-Evasion version

2.26.4
OS Used - all info (architecture, linux flavor, etc)

Kali Linux 2.0
Pastebin link to error you are encountering (include console actions you
took prior to error)

The program works fine as long as I'm not trying to use 64bit architecture,
but as soon as I try to, it cannot create the payload. I am aware the LHOST
in the paste says 0.0.0.0, I did that just for the
paste. Here is the link to the pastebin.

http://pastebin.com/wMdyk5Te
Expected behavior

It won't create a payload with 64bit architecture.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Veil-Framework/Veil-Evasion/issues/343>, or mute the
thread
<https://github.com/notifications/unsubscribe/ABmORsqw1IkE5ast07mvOdPsSt2l2AICks5qG3_JgaJpZM4IqFtP>
.

**Comment by Illurity** [comment]
@ChrisTruncer Thank you for the fast response, I'm somewhat new to Kali, do you mind telling me how I would use the 64bit source output to generate x64 payloads?

**Comment by ChrisTruncer** [comment]
You will need to install x64 wine and all of Veil's dependencies.

Thanks!
