### ISSUE TITLE
Veil error libpng16.so.16

### ISSUE THREAD

**Issue by cacaocaca** [Veil-Framework/Veil-Evasion#356]
## Veil-Evasion version

2.27

## OS Used - all info (architecture, linux flavor, etc)
kali linux rolled 

## Pastebin link to error you are encountering (include console actions you took prior to error)
https://s31.postimg.org/493caaup7/veil.png

## Any additional info you want to tell me
How i can resolve this error ?

**Comment by ChrisTruncer** [comment]
Did you try to generate a ruby payload?  This looks like normal debug output.  Please generate a payload to test if it works first before reporting an issue.

Thanks

**Comment by cacaocaca** [comment]
yes i try now i have upgrage kali linux 2.0 to rolling and in at the end have this error https://forums.kali.org/showthread.php?30176-issues-upgrading-from-kali-2-0-to-2016-1-rolling . Afther when i reboot i do lsb_release -a and show me kali linux 2.0 so i do again apt-get upgrade waiting and now he show me kali linux rolling but i think this is the problem .. Now i have do on veil python/shellcode_inject/arc_encrypt  -> generate > windows/meterpreter/reverse_tcp -> LHOST 192.168.1.100 -> LPORT 443 -> Enter -> afther when i choose Pyinstaller i have this error https://s32.postimg.org/qucyihmmt/veil.png and i have already run first python update.py

**Comment by ChrisTruncer** [comment]
Please start from a clean Kali Rolling VM.


-----------------------------------------------------------------------------------------
Christopher Truncer
@christruncer <http://www.twitter.com/christruncer>

On June 20, 2016 at 9:36:24 AM, cacaocaca (notifications@github.com) wrote:

yes i try now i have upgrage kali linux 2.0 to rolling and in at the end
have this error
https://forums.kali.org/showthread.php?30176-issues-upgrading-from-kali-2-0-to-2016-1-rolling
. Afther when i reboot i do lsb_release -a and show me kali linux 2.0 so i
do again apt-get upgrade waiting and now he show me kali linux rolling but
i think this is the problem .. Now i have do on veil
python/shellcode_inject/arc_encrypt -> generate >
windows/meterpreter/reverse_tcp -> LHOST 192.168.1.100 -> LPORT 443 ->
Enter -> afther when i choose Pyinstaller i have this error
https://s32.postimg.org/qucyihmmt/veil.png and i have already run first
python update.py

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/Veil-Framework/Veil-Evasion/issues/356#issuecomment-227179174>,
or mute the thread
<https://github.com/notifications/unsubscribe/ABmORuKrjEYoAY7ilnXHfhPaxYx1DpG7ks5qNrN4gaJpZM4I5zIu>
.

**Comment by cacaocaca** [comment]
While i have to install Veil i have look already this error of libpng16.so.16 but  i have wait the finish to install is the first time happen it .. So i can t how resolve this error on internet don t exists anyone guide to resolve it https://forums.kali.org/showthread.php?30176-issues-upgrading-from-kali-2-0-to-2016-1-rolling  i can t format the pc and install kali rolling againt just for work Veil is more good find one solution

**Comment by cacaocaca** [comment]
Sorry but i dont understand good what is the reposity right of kali rolling http://null-byte.wonderhowto.com/forum/failed-install-veil-evasion-kali-linux-and-rolling-0169870/
deb http://http.kali.org/kali kali-rolling main non-free contrib
or
deb http://http.kali.org/kali kali-rolling main contrib non-free
Is same ?

**Comment by cacaocaca** [comment]
I have format i have kali linux rolling Linux kali 4.5.0-kali1-686-pae #1 SMP Debian 4.5.5-1kali1 (2016-06-06) i686 GNU/Linux so the problem now is of my wine when  veil starting to generate shell code 
4022 INFO: checking PYZ
4023 INFO: Building PYZ because out00-PYZ.toc is non existent
4026 INFO: Building PYZ (ZlibArchive) Z:\root\Scrivania\Veil-Evasion\build\payload5\out00-PYZ.pyz
4453 INFO: checking PKG
4455 INFO: Building PKG because out00-PKG.toc is non existent
4457 INFO: Building PKG (CArchive) out00-PKG.pkg
4496 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 21022, 8)
5613 INFO: Bootloader Z:\usr\share\pyinstaller\PyInstaller\bootloader\Windows-32bit\runw.exe
5617 INFO: checking EXE
5618 INFO: Building EXE because out00-EXE.toc is non existent
5621 INFO: Building EXE from out00-EXE.toc
5625 INFO: Appending archive to EXE Z:\root\Scrivania\Veil-Evasion\dist\payload5.exe
The problem starting with wine i think look it https://s32.postimg.org/5o4i9kqo5/veil.png
The last terminal translate 
dpkg: warning: files list file for package 'python-ctypeslib' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'python-ecdsa' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'python-lzma' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'python-lzo' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'python-pyqtgraph' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'gccxml' missing; assuming package has no files currently installed 
It if the first terminal if look i try to start with wine winrar and he show me error of gecko.
On the two terminal i try to run payload with wine and dont  work is normally the problem is of wine-gecko .. I don  know becouse i have all this shit i have download clean  of kali 2.0 and afther upgrade to kali rolling . You can help me to solve it ?

**Comment by cacaocaca** [comment]
OK i have resolve it now when i run file create with veil https://postimg.org/image/3r43u00s1/

**Comment by cacaocaca** [comment]
You said me start with kali rolling and now dont  support more O_o ? I have format the pc cause your answer " kali linux rolling clean "
