### ISSUE TITLE
Conflict with metasploit

### ISSUE THREAD

**Issue by lizardpunk** [Veil-Framework/Veil-Evasion#365]
If you install veil-evasion, metasploit doesn't worked, veil changed ruby version and that damaged metasploit. I tried 2 times in VM of Kali Rolling x86 and the problem persisted.

**Comment by ChrisTruncer** [comment]
Please use the specified template for any future github issues.

Veil-Evasion does not modify Ruby within linux.  The only area Veil touches Ruby is within Wine, which is separate from what comes installed with Kali.

Could you point out where exactly Veil-Evasion modifies the ruby package that comes with Kali?

**Comment by lizardpunk** [comment]
this is the message, after install veil-evasion in metasploit

root@kali:~# msfconsole
/usr/lib/ruby/2.3.0/openssl.rb:13:in `require': /usr/lib/i386-linux-gnu/ruby/2.3.0/openssl.so: symbol SSLv2_method, version OPENSSL_1.0.2d not defined in file libssl.so.1.0.2 with link time reference - /usr/lib/i386-linux-gnu/ruby/2.3.0/openssl.so (LoadError)
	from /usr/lib/ruby/2.3.0/openssl.rb:13:in `<top (required)>'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/bcrypt-3.1.11/lib/bcrypt.rb:9:in `require'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/bcrypt-3.1.11/lib/bcrypt.rb:9:in `<top (required)>'
	from /usr/share/metasploit-framework/lib/metasploit/framework.rb:9:in `require'
	from /usr/share/metasploit-framework/lib/metasploit/framework.rb:9:in `<top (required)>'
	from /usr/share/metasploit-framework/lib/metasploit/framework/database.rb:1:in `require'
	from /usr/share/metasploit-framework/lib/metasploit/framework/database.rb:1:in `<top (required)>'
	from /usr/share/metasploit-framework/lib/metasploit/framework/parsed_options/base.rb:17:in `require'
	from /usr/share/metasploit-framework/lib/metasploit/framework/parsed_options/base.rb:17:in `<top (required)>'
	from /usr/share/metasploit-framework/lib/metasploit/framework/parsed_options/console.rb:2:in `require'
	from /usr/share/metasploit-framework/lib/metasploit/framework/parsed_options/console.rb:2:in `<top (required)>'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:263:in `require'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:263:in `const_get'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:263:in `block in constantize'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:259:in `each'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:259:in `inject'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:259:in `constantize'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:73:in `parsed_options_class'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:69:in `parsed_options'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:47:in `require_environment!'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:81:in `start'
	from /usr/bin/msfconsole:48:in `<main>'
root@kali:~#

**Comment by veil-evasion** [comment]
Again, Veil doesn’t modify anything within that path.  The only time it
does anything related to Ruby is within Wine.  If you can show me where in
Veil this change is modified I will address it immediately, but Veil
doesn’t touch any of those locations.

-----------------------------------------------------------------------------------------
Christopher Truncer
@christruncer <http://www.twitter.com/christruncer>

On June 28, 2016 at 1:03:48 PM, lizardpunk (notifications@github.com) wrote:

this is the message, after install veil-evasion in metasploit

root@kali:~# msfconsole
/usr/lib/ruby/2.3.0/openssl.rb:13:in require':
/usr/lib/i386-linux-gnu/ruby/2.3.0/openssl.so: symbol SSLv2_method, version
OPENSSL_1.0.2d not defined in file libssl.so.1.0.2 with link time reference
- /usr/lib/i386-linux-gnu/ruby/2.3.0/openssl.so (LoadError)
from /usr/lib/ruby/2.3.0/openssl.rb:13:in'
from
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/bcrypt-3.1.11/lib/bcrypt.rb:9:in
require'
from
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/bcrypt-3.1.11/lib/bcrypt.rb:9:in
'
from /usr/share/metasploit-framework/lib/metasploit/framework.rb:9:in
require'
from /usr/share/metasploit-framework/lib/metasploit/framework.rb:9:in'
from
/usr/share/metasploit-framework/lib/metasploit/framework/database.rb:1:in
require'
from
/usr/share/metasploit-framework/lib/metasploit/framework/database.rb:1:in'
from
/usr/share/metasploit-framework/lib/metasploit/framework/parsed_options/base.rb:17:in
require'
from
/usr/share/metasploit-framework/lib/metasploit/framework/parsed_options/base.rb:17:in
'
from
/usr/share/metasploit-framework/lib/metasploit/framework/parsed_options/console.rb:2:in
require'
from
/usr/share/metasploit-framework/lib/metasploit/framework/parsed_options/console.rb:2:in
'
from
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:263:in
require'
from
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:263:in
const_get'
from
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:263:in
block in constantize'
from
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:259:in
each'
from
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:259:in
inject'
from
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:259:in
constantize'
from
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/core_ext/string/inflections.rb:66:in
constantize'
from
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:73:in
parsed_options_class'
from
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:69:in
parsed_options'
from
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:47:in
require_environment!'
from
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:81:in
start'
from /usr/bin/msfconsole:48:in
'
root@kali:~#

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Veil-Framework/Veil-Evasion/issues/365#issuecomment-229149624>,
or mute the thread
<https://github.com/notifications/unsubscribe/AEX0zn4k1k1t9CBs0HnsfhTAhrKrgOx8ks5qQXAUgaJpZM4JAa05>
.

**Comment by lizardpunk** [comment]
the installation of veil-evasion disabled metaploit, that's it, sorry if i didn't explain correctly the problem

**Comment by ChrisTruncer** [comment]
Veil-Evasion does not disable metasploit

**Comment by lizardpunk** [comment]
the problem is in metasploit, sorry for the confusion, thanks

**Comment by femskey** [comment]
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.

Could not load OpenSSL.
You must recompile Ruby with OpenSSL support or change the sources in your
Gemfile from 'https' to 'http'. Instructions for compiling with OpenSSL using
RVM are available at http://rvm.io/packages/openssl.

**Comment by femskey** [comment]
pls help me with this problem
