### ISSUE TITLE
[ERROR] Failed to install Wine... Exit Code: 100.

### ISSUE THREAD

**Issue by cneita** [Veil-Framework/Veil-Evasion#385]
what can i do to fix this problem, each time i go to install the setup i get this message:
https://gyazo.com/5ad6b3bb0266224a27fe531c44b84b0e

Im running this install on a fresh install of kali and still getting this problem. Also tried changing my sources.list file to:
https://gyazo.com/c60995427681afd6605f82b101fe6e9f

still no luck, please help :(

ive checked all the other closed issues and none fix the issue

**Comment by veil-evasion** [comment]
It is your repos, this has been answered many times before. The sana repos are now retired.

Please use the template for filling out github issues in the future as it helps to provide some of the information I need to help troubleshoot.

**Comment by cneita** [comment]
Thanks for your quick response, i have gone through literally every other post about this issue and every answer uses those same sana repos, would you mind telling me which ones i should change to??

**Comment by YourDa** [comment]
I am having the same problems. My repos at the moment are:
# Regular repositories
deb http://http.kali.org/kali sana main non-free contrib
deb http://security.kali.org/kali-security sana/updates main contrib non-free
# Source repositories
deb-src http://http.kali.org/kali sana main non-free contrib
deb-src http://security.kali.org/kali-security sana/updates main contrib non-free

I run bash setup/setup.sh -s
and then I am greeted with the same WINE exit 100 error. It says it may be because of withheld repos, if somebody could just list some raw paste text of something that people can paste into their sources.list, then the wine exit 100 issue should not be appearing anymore in these issues as people will be able to fix it with the paste data.

**Comment by ChrisTruncer** [comment]
Please look online.  The Kal developers said sana repos are retired

**Comment by YourDa** [comment]
I dont think you read this properly, I can not find the repos for veil evasion. IK I'm being a nuisance but please update the repos

**Comment by r1Ns3** [comment]
Yes, don't just say they are retired, TELL us WHAT to replace it with please!

**Comment by Zeleckto** [comment]
Yes, I had a similar problem, Here is what i did to fix the problem.

change your sources.list file to : 
deb http://repo.kali.org/kali kali-rolling main contrib non-free
# deb-src http://repo.kali.org/kali kali-rolling main contrib non-free

apt-get update

apt- get install wine32

now go back to Veil Evasion and run the setup.sh again.

Worked for me.
