### ISSUE TITLE
AttributeError: 'module' object has no attribute 'WINEPREFIX'

### ISSUE THREAD

**Issue by psyqologicaL** [Veil-Framework/Veil-Evasion#386]
## Veil-Evasion version
2.28.1

## OS Used - all info (architecture, linux flavor, etc)
Kali Linux (x86_64)

## Pastebin link to error you are encountering (include console actions you took prior to error)
I used 34 (python/reverse_tcp)
Set my external IP
Set USE_PYHERION to Y
Chose the Pwninstaller (2) instead the default Pyinstaller (1)
Typed in the name and then this happened
http://pastebin.com/SeLUvhyr

## Expected behavior
It should have simply generated the payload.

## Any additional info you want to tell me
Removed it and installed it again (with git clone ofc)
Also updated and upgraded my Kali.
Is it maybe because I created a folder (tools) and cloned it in there?

**Comment by veil-evasion** [comment]
Can you run the update.py script?  You should have the variable within your
settings file


-----------------------------------------------------------------------------------------
Christopher Truncer
@christruncer <http://www.twitter.com/christruncer>

On September 2, 2016 at 10:03:10 AM, psyqologicaL (notifications@github.com)
wrote:

Veil-Evasion version

2.28.1
OS Used - all info (architecture, linux flavor, etc)

Kali Linux (x86_64)
Pastebin link to error you are encountering (include console actions you
took prior to error)

I used 34 (python/reverse_tcp)
Set my external IP
Set USE_PYHERION to Y
Chose the Pwninstaller (2) instead the default Pyinstaller (1)
Typed in the name and then this happened
http://pastebin.com/SeLUvhyr
Expected behavior

It should have simply generated the payload.
Any additional info you want to tell me

Removed it and installed it again (with git clone ofc)
Also updated and upgraded my Kali.
Is it maybe because I created a folder (tools) and cloned it in there?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Veil-Framework/Veil-Evasion/issues/386>, or mute the
thread

**Comment by psyqologicaL** [comment]
Thanks a lot, it worked. I kinda overlooked it.
