### ISSUE TITLE
64bit payloads generated as 32bit

### ISSUE THREAD

**Issue by kegra** [Veil-Framework/Veil-Evasion#398]
## Veil-Evasion version
Veil-Evasion | [Version]: 2.28.2

## OS Used - all info (architecture, linux flavor, etc)
Linux kali 4.7.0-kali1-amd64 #1 SMP Debian 4.7.5-1kali3 (2016-09-29) x86_64 GNU/Linux

## Pastebin link to error you are encountering (include console actions you took prior to error)
Payload information:

	Name:		python/meterpreter/rev_tcp
	Language:	python
	Rating:		Excellent
	Description:    pure windows/meterpreter/reverse_tcp stager, no
	                shellcode

 Required Options:

 Name			Current Value	Description
 ----			-------------	-----------
 ARCHITECTURE    	64      	Select the final binary architecture (32, 64)
 COMPILE_TO_EXE  	Y       	Compile to an executable
 EXPIRE_PAYLOAD  	X       	Optional: Payloads expire after "Y" days ("X" disables feature)
 LHOST           	192.168.1.250	IP of the Metasploit handler
 LPORT           	443     	Port of the Metasploit handler
 USE_PYHERION    	Y       	Use the pyherion encrypter

## Expected behaviour
to produce a 64bit payload , but after executing to target host the process shows as x86 

## Any additional info you want to tell me
=========================================================================
 Veil-Evasion | [Version]: 2.28.2
=========================================================================
 [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
=========================================================================

 [>] Please enter the base name for output files (default is 'payload'): test

 [?] How would you like to create your payload executable?

     1 - Pyinstaller (default)
 [>] Please enter the number of your choice: 1
err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
992 INFO: PyInstaller: 3.2
1000 INFO: Python: 2.7.5
1009 INFO: Platform: Windows-2003Server-5.2.3790-SP2
1039 INFO: wrote Z:\usr\share\veil-evasion\test1.spec
1068 INFO: UPX is not available.
1098 INFO: Extending PYTHONPATH with paths
['Z:\\var\\lib\\veil-evasion\\output\\source', 'Z:\\usr\\share\\veil-evasion']
1124 INFO: Will encrypt Python bytecode with key: 00000000kzUQYzly
1129 INFO: Adding dependencies on pyi_crypto.py module
1136 INFO: checking Analysis
1140 INFO: Building Analysis because out00-Analysis.toc is non existent
1154 INFO: Initializing module dependency graph...
1174 INFO: Initializing module graph hooks...
1307 INFO: Analyzing hidden import 'Crypto.Cipher._AES'
1373 INFO: running Analysis out00-Analysis.toc
1407 INFO: Adding Microsoft.VC90.CRT to dependent assemblies of final executable
  required by C:\Python27\python.exe
1459 INFO: Found C:\windows\WinSxS\Policies\x86_policy.9.0.Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_x-ww_b7353f75\9.0.21022.8.policy
1513 INFO: Searching for assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.21022.8_x-ww ...
1548 INFO: Found manifest C:\windows\WinSxS\Manifests\x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.21022.8_x-ww_d08d0375.manifest
1605 INFO: Searching for file msvcr90.dll
1618 INFO: Found file C:\windows\WinSxS\x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.21022.8_x-ww_d08d0375\msvcr90.dll
1662 INFO: Searching for file msvcp90.dll
1676 INFO: Found file C:\windows\WinSxS\x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.21022.8_x-ww_d08d0375\msvcp90.dll
1718 INFO: Searching for file msvcm90.dll
1736 INFO: Found file C:\windows\WinSxS\x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.21022.8_x-ww_d08d0375\msvcm90.dll
1778 INFO: Found C:\windows\WinSxS\Policies\x86_policy.9.0.Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_x-ww_b7353f75\9.0.21022.8.policy
1832 INFO: Adding redirect Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 21022, 8)
8952 INFO: Caching module hooks...
8985 INFO: Analyzing \var\lib\veil-evasion\output\source\test1.py
10810 INFO: Loading module hooks...
10812 INFO: Loading module hook "hook-encodings.py"...
11511 INFO: Looking for ctypes DLLs
11513 INFO: Analyzing run-time hooks ...

**Comment by ChrisTruncer** [comment]
Yeah, this is due to the way the environment is setup.  If you want x64 payloads, you have to install 64 bit wine, python, and the required libraries.  By default Veil installs the x86 version of everything.  So it is possible to do this, but you need to just manually setup your environment.

**Comment by reza-boy** [comment]
that's fine just would you please let us know the list of required libraries for generating  x64 payloads with Veil ???
thanks in advance

**Comment by ChrisTruncer** [comment]
@reza-boy - this project isn't supported, please see the giant message at the top.

Also, did you just try the 64 bit versions of the current packages? :/

**Comment by necrose99** [comment]
i have a few scripts in my havent had time to twek with necromancy overlay repo more geared for Pentoo/Gentoo Linux..  however its a [winetricks](https://wiki.winehq.org/Winetricks) setup script 
https://github.com/necrose99/necromancy-overlay/tree/master/app-emulation/veil-wine 
files 

since Veil tools are supported by pentoo and not by veil directly hear are a few wrappers..  

at the time i did suggest to the veil team to use a wine prefix ie veil , as if you had the weekend warrior wine profile for wine games adding to a primary as thus the wont clobber each other .. 
(which they happen to have done) 

the python etc is stale , however you can tweak the scripts to pull in a fully specked veil 
and change to 64 bit..  (I've had my hands full otherwise..   not like i could get a whole year paid researcher vacation.....)
anyhow its winetricks , wget to dir eggs wheels etc python 2.7.x 3.6.x etc.. 
winetricks or wget packages add to that prefix.. 
at the time I was also working on a back up hashes script , but a burn baby burn script also.. 
not like the law was going to kick in the door , but , each pen-test assignment idea was to clean out the dead..  and also wise to file shred the $user/.veil-64 /.veil prefixes.. 
 https://raw.githubusercontent.com/necrose99/necromancy-overlay/master/app-emulation/veil-wine/files/veil-wine64-setup.sh
_**as mentioned the templates a bit  stale**_ , however you can tweak & Twerk  them to a prefix for wine setup etc  for your needs including any tools for analysis etc..  or desired pip packages.. 
for a majority of Linux types..  
[activepython](https://www.activestate.com/activepython)  has a good number of windows packages already baked into python.  winetricks can quite easly see if any missing depednds and wrap the msi ... 

 anyhow winetricks has a list of packages it will go fetch or if url i think is provided will go get..  least a fare number of them ... 
and or wget wintricks install others.. , it tends to run like apt-get , &/else you can abuse  [Chocolatey](https://chocolatey.org/packages) also like apt-get  NUPKG  to deploy more tedious ones not in winetricks.. 
( I abuse to deploy windows workstations etc. for small business customers.. and "automagically" get windows updates etc..) 
https://github.com/PlayOnLinux/POL-POM-4 https://www.playonlinux.com/en/download.html 
sure its a a game focused enviro , however it dose do powershell installs etc.  and for veil powershell testing could be of use.  likewise similar  to winetricks an another util for scripting a 64bit or 32bit veil setup with more custom tools or base+ addons.. ie debuggers etc... 

(**in theory you could get veil to run on windows 10..** https://github.com/GoSecure/malboxes) also uses chocolatey too keep  windows packages fresh..   **and is a test lab for malware reversing or analysis - one could use veil for just how far the rabbit hole goes down.**  and or how effective AI engines are ie Cylance or good AV ie Clients AV is at catching you.
