### ISSUE TITLE
[Feature Request] Detection Reporting

### ISSUE THREAD

**Issue by zero77** [Veil-Framework/Veil-Evasion#413]
Can you build in the option for people to anonymously report if a payload has been detected by a specific AV, which would then appear in the payload menu and show which AV it was detected by in the payload info section.
Thanks

**Comment by cacaocaca** [comment]
He need integrate scan with upload and i don t think is possible but can you make check by hash and I do not think you just have to use veil to generate a fud you need to combine but i  answer to your question
On  Available Commands:
	use         	Use a specific payload
	info        	Information on a specific payload
	list        	List available payloads
	update      	Update Veil-Evasion to the latest version
	clean       	Clean out payload folders
	checkvt     	Check payload hashes vs. VirusTotal
	exit        	Exit Veil-Evasion
You can see " checkvt" so text checkvt but the problem is that hash don t found becouse while you make a payload on veil the hash is always  different  but you can do it on kali on terminal
md5sum /root/Scrivania/payload91.exe
bf3956506d7a145712252c7e118e4de8  /root/Scrivania/payload91.exe
He show the md5 hash afther go on virustotal and click on search and put the hash but remember dont  upload file on virustotal he share the sample to companie if you payload have 5 detected today afther some days your payload  is detected as 10 av it becouse he share sample to av so you can upload the file direct on another scan online as https://ziscan.com/ is fast and easy he don t distribute sample at least so he says .
 Have Good days .

**Comment by ChrisTruncer** [comment]
That would be a great idea.  At the moment, I don't have the time to get this added in, but I would be happy to review a pull request with this feature added.
