### ISSUE TITLE
dynamic dns 

### ISSUE THREAD

**Issue by ayhaga** [Veil-Framework/Veil-Evasion#97]
i have a front name www.whatever.com  that will get resolved into my ip address how can i add it to LHOST as it responds with bad hostname error
thank you

**Comment by ChrisTruncer** [comment]
Hi there,

You didn't provide enough information for me to test anything with.  If you're using a domain name, it's going to resolve the IP address, and then store the IP within the payload.  In order to use a dns name, you need to use reverse_tcp_dns or something similar to resolve the domain name each time.

**Comment by ayhaga** [comment]
i am sorry if i didn`t provide enough information 
yes i am using a domain name that is supposed to be resolved into my ip address
there is no reverse_tcp_dns in the list of payloads, only reverse_tcp_service
and its only by c language and that gets caught easily 
thank you

**Comment by ayhaga** [comment]
actually now i tried once more and the error (bad hostname) no longer occurs !!!!!..but i am using it on ruby/meterpreter/reverse_https_contained ,are you saying that this payload won`t be able to get it  resolved and only reverse_tcp_dns will be able to do it..
thanks once more

**Comment by ChrisTruncer** [comment]
The shellcode you are generating needs to be reverse_tcp_dns
